#Beginning of Config
#Authors willies952002, Clarkcj
#Version 0.1
craft:
  sand:
    red: true
    white: true
  blazerod: true
  nametag: true
smelt:
  sponge: true
brew:
  expBottle: true
  enchantBottle:true
  