name: Uncraftables
main: com.domnian.Uncraftables.Uncraftables
description: >
   A plugin allowing you to be able to craft uncraftable items/blocks
version: 0.1
author: willies952002
authors: [willies952002, Clarkcj]
